//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func (in *PowerDNSServer) DeepCopyInto(out *PowerDNSServer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *PowerDNSServer) DeepCopy() *PowerDNSServer {
	if in == nil {
		return nil
	}
	out := new(PowerDNSServer)
	in.DeepCopyInto(out)
	return out
}

func (in *PowerDNSServer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *PowerDNSServerList) DeepCopyInto(out *PowerDNSServerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		l := make([]PowerDNSServer, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&l[i])
		}
		out.Items = l
	}
}

func (in *PowerDNSServerList) DeepCopy() *PowerDNSServerList {
	if in == nil {
		return nil
	}
	out := new(PowerDNSServerList)
	in.DeepCopyInto(out)
	return out
}

func (in *PowerDNSServerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *PowerDNSServerSpec) DeepCopyInto(out *PowerDNSServerSpec) {
	*out = *in
	if in.Replicas != nil {
		v := *in.Replicas
		out.Replicas = &v
	}
	in.Resources.DeepCopyInto(&out.Resources)
	in.Backend.DeepCopyInto(&out.Backend)
	in.DNS.DeepCopyInto(&out.DNS)
	in.API.DeepCopyInto(&out.API)
	in.Scheduling.DeepCopyInto(&out.Scheduling)
	in.Observability.DeepCopyInto(&out.Observability)
	in.NetworkPolicy.DeepCopyInto(&out.NetworkPolicy)
}

func (in *SchedulingSpec) DeepCopyInto(out *SchedulingSpec) {
	*out = *in
	if in.NodeSelector != nil {
		m := make(map[string]string, len(in.NodeSelector))
		for k, v := range in.NodeSelector {
			m[k] = v
		}
		out.NodeSelector = m
	}
	if in.Tolerations != nil {
		l := make([]corev1.Toleration, len(in.Tolerations))
		for i := range in.Tolerations {
			in.Tolerations[i].DeepCopyInto(&l[i])
		}
		out.Tolerations = l
	}
}

func (in *SchedulingSpec) DeepCopy() *SchedulingSpec {
	if in == nil {
		return nil
	}
	out := new(SchedulingSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *ObservabilitySpec) DeepCopyInto(out *ObservabilitySpec) {
	*out = *in
	in.PodMonitor.DeepCopyInto(&out.PodMonitor)
}

func (in *ObservabilitySpec) DeepCopy() *ObservabilitySpec {
	if in == nil {
		return nil
	}
	out := new(ObservabilitySpec)
	in.DeepCopyInto(out)
	return out
}

func (in *PodMonitorSpec) DeepCopyInto(out *PodMonitorSpec) {
	*out = *in
	if in.Labels != nil {
		m := make(map[string]string, len(in.Labels))
		for k, v := range in.Labels {
			m[k] = v
		}
		out.Labels = m
	}
}

func (in *PodMonitorSpec) DeepCopy() *PodMonitorSpec {
	if in == nil {
		return nil
	}
	out := new(PodMonitorSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *NetworkPolicySpec) DeepCopyInto(out *NetworkPolicySpec) {
	*out = *in
	if in.AdditionalAllowedAPINamespaces != nil {
		l := make([]string, len(in.AdditionalAllowedAPINamespaces))
		copy(l, in.AdditionalAllowedAPINamespaces)
		out.AdditionalAllowedAPINamespaces = l
	}
}

func (in *NetworkPolicySpec) DeepCopy() *NetworkPolicySpec {
	if in == nil {
		return nil
	}
	out := new(NetworkPolicySpec)
	in.DeepCopyInto(out)
	return out
}

func (in *PowerDNSServerSpec) DeepCopy() *PowerDNSServerSpec {
	if in == nil {
		return nil
	}
	out := new(PowerDNSServerSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *BackendSpec) DeepCopyInto(out *BackendSpec) {
	*out = *in
	if in.Postgres != nil {
		out.Postgres = new(PostgresBackendSpec)
		in.Postgres.DeepCopyInto(out.Postgres)
	}
}

func (in *BackendSpec) DeepCopy() *BackendSpec {
	if in == nil {
		return nil
	}
	out := new(BackendSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *PostgresBackendSpec) DeepCopyInto(out *PostgresBackendSpec) {
	*out = *in
	if in.Instances != nil {
		v := *in.Instances
		out.Instances = &v
	}
	if in.BYO != nil {
		out.BYO = new(BYOPostgres)
		*out.BYO = *in.BYO
	}
}

func (in *PostgresBackendSpec) DeepCopy() *PostgresBackendSpec {
	if in == nil {
		return nil
	}
	out := new(PostgresBackendSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *BYOPostgres) DeepCopyInto(out *BYOPostgres) { *out = *in }

func (in *BYOPostgres) DeepCopy() *BYOPostgres {
	if in == nil {
		return nil
	}
	out := new(BYOPostgres)
	in.DeepCopyInto(out)
	return out
}

func (in *DNSSpec) DeepCopyInto(out *DNSSpec) {
	*out = *in
	if in.LoadBalancer != nil {
		out.LoadBalancer = new(DNSLoadBalancerSpec)
		in.LoadBalancer.DeepCopyInto(out.LoadBalancer)
	}
	if in.Gateway != nil {
		out.Gateway = new(DNSGatewaySpec)
		in.Gateway.DeepCopyInto(out.Gateway)
	}
}

func (in *DNSSpec) DeepCopy() *DNSSpec {
	if in == nil {
		return nil
	}
	out := new(DNSSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *DNSLoadBalancerSpec) DeepCopyInto(out *DNSLoadBalancerSpec) {
	*out = *in
	if in.Annotations != nil {
		m := make(map[string]string, len(in.Annotations))
		for k, v := range in.Annotations {
			m[k] = v
		}
		out.Annotations = m
	}
	if in.AdditionalServices != nil {
		l := make([]AdditionalLoadBalancerService, len(in.AdditionalServices))
		for i := range in.AdditionalServices {
			in.AdditionalServices[i].DeepCopyInto(&l[i])
		}
		out.AdditionalServices = l
	}
}

func (in *DNSLoadBalancerSpec) DeepCopy() *DNSLoadBalancerSpec {
	if in == nil {
		return nil
	}
	out := new(DNSLoadBalancerSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *AdditionalLoadBalancerService) DeepCopyInto(out *AdditionalLoadBalancerService) {
	*out = *in
	if in.Annotations != nil {
		m := make(map[string]string, len(in.Annotations))
		for k, v := range in.Annotations {
			m[k] = v
		}
		out.Annotations = m
	}
}

func (in *AdditionalLoadBalancerService) DeepCopy() *AdditionalLoadBalancerService {
	if in == nil {
		return nil
	}
	out := new(AdditionalLoadBalancerService)
	in.DeepCopyInto(out)
	return out
}

func (in *DNSGatewaySpec) DeepCopyInto(out *DNSGatewaySpec) {
	*out = *in
	if in.ParentRefs != nil {
		l := make([]GatewayParentRef, len(in.ParentRefs))
		copy(l, in.ParentRefs)
		out.ParentRefs = l
	}
}

func (in *DNSGatewaySpec) DeepCopy() *DNSGatewaySpec {
	if in == nil {
		return nil
	}
	out := new(DNSGatewaySpec)
	in.DeepCopyInto(out)
	return out
}

func (in *APISpec) DeepCopyInto(out *APISpec) {
	*out = *in
	if in.APIKeySecretRef != nil {
		ref := *in.APIKeySecretRef
		out.APIKeySecretRef = &ref
	}
}

func (in *APISpec) DeepCopy() *APISpec {
	if in == nil {
		return nil
	}
	out := new(APISpec)
	in.DeepCopyInto(out)
	return out
}

func (in *PowerDNSServerStatus) DeepCopyInto(out *PowerDNSServerStatus) {
	*out = *in
	if in.Conditions != nil {
		l := make([]v1.Condition, len(in.Conditions))
		for i := range in.Conditions {
			in.Conditions[i].DeepCopyInto(&l[i])
		}
		out.Conditions = l
	}
}

func (in *PowerDNSServerStatus) DeepCopy() *PowerDNSServerStatus {
	if in == nil {
		return nil
	}
	out := new(PowerDNSServerStatus)
	in.DeepCopyInto(out)
	return out
}
