//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func (in *PowerDNSServer) DeepCopyInto(out *PowerDNSServer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *PowerDNSServer) DeepCopy() *PowerDNSServer {
	if in == nil {
		return nil
	}
	out := new(PowerDNSServer)
	in.DeepCopyInto(out)
	return out
}

func (in *PowerDNSServer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *PowerDNSServerList) DeepCopyInto(out *PowerDNSServerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		l := make([]PowerDNSServer, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&l[i])
		}
		out.Items = l
	}
}

func (in *PowerDNSServerList) DeepCopy() *PowerDNSServerList {
	if in == nil {
		return nil
	}
	out := new(PowerDNSServerList)
	in.DeepCopyInto(out)
	return out
}

func (in *PowerDNSServerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *PowerDNSServerSpec) DeepCopyInto(out *PowerDNSServerSpec) {
	*out = *in
	if in.Replicas != nil {
		v := *in.Replicas
		out.Replicas = &v
	}
	in.Resources.DeepCopyInto(&out.Resources)
	in.Backend.DeepCopyInto(&out.Backend)
	in.DNS.DeepCopyInto(&out.DNS)
	in.API.DeepCopyInto(&out.API)
	in.Scheduling.DeepCopyInto(&out.Scheduling)
	in.Observability.DeepCopyInto(&out.Observability)
	in.NetworkPolicy.DeepCopyInto(&out.NetworkPolicy)
	in.ZoneManagement.DeepCopyInto(&out.ZoneManagement)
	if in.PodDisruptionBudget != nil {
		out.PodDisruptionBudget = new(PDBSpec)
		in.PodDisruptionBudget.DeepCopyInto(out.PodDisruptionBudget)
	}
}

func (in *SchedulingSpec) DeepCopyInto(out *SchedulingSpec) {
	*out = *in
	if in.NodeSelector != nil {
		m := make(map[string]string, len(in.NodeSelector))
		for k, v := range in.NodeSelector {
			m[k] = v
		}
		out.NodeSelector = m
	}
	if in.Tolerations != nil {
		l := make([]corev1.Toleration, len(in.Tolerations))
		for i := range in.Tolerations {
			in.Tolerations[i].DeepCopyInto(&l[i])
		}
		out.Tolerations = l
	}
}

func (in *SchedulingSpec) DeepCopy() *SchedulingSpec {
	if in == nil {
		return nil
	}
	out := new(SchedulingSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *ObservabilitySpec) DeepCopyInto(out *ObservabilitySpec) {
	*out = *in
	in.PodMonitor.DeepCopyInto(&out.PodMonitor)
}

func (in *ObservabilitySpec) DeepCopy() *ObservabilitySpec {
	if in == nil {
		return nil
	}
	out := new(ObservabilitySpec)
	in.DeepCopyInto(out)
	return out
}

func (in *PodMonitorSpec) DeepCopyInto(out *PodMonitorSpec) {
	*out = *in
	if in.Labels != nil {
		m := make(map[string]string, len(in.Labels))
		for k, v := range in.Labels {
			m[k] = v
		}
		out.Labels = m
	}
}

func (in *PodMonitorSpec) DeepCopy() *PodMonitorSpec {
	if in == nil {
		return nil
	}
	out := new(PodMonitorSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *NetworkPolicySpec) DeepCopyInto(out *NetworkPolicySpec) {
	*out = *in
	if in.AdditionalAllowedAPINamespaces != nil {
		l := make([]string, len(in.AdditionalAllowedAPINamespaces))
		copy(l, in.AdditionalAllowedAPINamespaces)
		out.AdditionalAllowedAPINamespaces = l
	}
}

func (in *NetworkPolicySpec) DeepCopy() *NetworkPolicySpec {
	if in == nil {
		return nil
	}
	out := new(NetworkPolicySpec)
	in.DeepCopyInto(out)
	return out
}

func (in *PowerDNSServerSpec) DeepCopy() *PowerDNSServerSpec {
	if in == nil {
		return nil
	}
	out := new(PowerDNSServerSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *BackendSpec) DeepCopyInto(out *BackendSpec) {
	*out = *in
	if in.Postgres != nil {
		out.Postgres = new(PostgresBackendSpec)
		in.Postgres.DeepCopyInto(out.Postgres)
	}
}

func (in *BackendSpec) DeepCopy() *BackendSpec {
	if in == nil {
		return nil
	}
	out := new(BackendSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *PostgresBackendSpec) DeepCopyInto(out *PostgresBackendSpec) {
	*out = *in
	if in.Instances != nil {
		v := *in.Instances
		out.Instances = &v
	}
	if in.BYO != nil {
		out.BYO = new(BYOPostgres)
		*out.BYO = *in.BYO
	}
}

func (in *PostgresBackendSpec) DeepCopy() *PostgresBackendSpec {
	if in == nil {
		return nil
	}
	out := new(PostgresBackendSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *BYOPostgres) DeepCopyInto(out *BYOPostgres) { *out = *in }

func (in *BYOPostgres) DeepCopy() *BYOPostgres {
	if in == nil {
		return nil
	}
	out := new(BYOPostgres)
	in.DeepCopyInto(out)
	return out
}

func (in *DNSSpec) DeepCopyInto(out *DNSSpec) {
	*out = *in
	if in.LoadBalancer != nil {
		out.LoadBalancer = new(DNSLoadBalancerSpec)
		in.LoadBalancer.DeepCopyInto(out.LoadBalancer)
	}
	if in.Gateway != nil {
		out.Gateway = new(DNSGatewaySpec)
		in.Gateway.DeepCopyInto(out.Gateway)
	}
}

func (in *DNSSpec) DeepCopy() *DNSSpec {
	if in == nil {
		return nil
	}
	out := new(DNSSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *DNSLoadBalancerSpec) DeepCopyInto(out *DNSLoadBalancerSpec) {
	*out = *in
	if in.Annotations != nil {
		m := make(map[string]string, len(in.Annotations))
		for k, v := range in.Annotations {
			m[k] = v
		}
		out.Annotations = m
	}
	if in.AdditionalServices != nil {
		l := make([]AdditionalLoadBalancerService, len(in.AdditionalServices))
		for i := range in.AdditionalServices {
			in.AdditionalServices[i].DeepCopyInto(&l[i])
		}
		out.AdditionalServices = l
	}
}

func (in *DNSLoadBalancerSpec) DeepCopy() *DNSLoadBalancerSpec {
	if in == nil {
		return nil
	}
	out := new(DNSLoadBalancerSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *AdditionalLoadBalancerService) DeepCopyInto(out *AdditionalLoadBalancerService) {
	*out = *in
	if in.Annotations != nil {
		m := make(map[string]string, len(in.Annotations))
		for k, v := range in.Annotations {
			m[k] = v
		}
		out.Annotations = m
	}
}

func (in *AdditionalLoadBalancerService) DeepCopy() *AdditionalLoadBalancerService {
	if in == nil {
		return nil
	}
	out := new(AdditionalLoadBalancerService)
	in.DeepCopyInto(out)
	return out
}

func (in *DNSGatewaySpec) DeepCopyInto(out *DNSGatewaySpec) {
	*out = *in
	if in.ParentRefs != nil {
		l := make([]GatewayParentRef, len(in.ParentRefs))
		copy(l, in.ParentRefs)
		out.ParentRefs = l
	}
}

func (in *DNSGatewaySpec) DeepCopy() *DNSGatewaySpec {
	if in == nil {
		return nil
	}
	out := new(DNSGatewaySpec)
	in.DeepCopyInto(out)
	return out
}

func (in *APISpec) DeepCopyInto(out *APISpec) {
	*out = *in
	if in.APIKeySecretRef != nil {
		ref := *in.APIKeySecretRef
		out.APIKeySecretRef = &ref
	}
	if in.Gateway != nil {
		out.Gateway = new(APIGatewaySpec)
		in.Gateway.DeepCopyInto(out.Gateway)
	}
}

func (in *APISpec) DeepCopy() *APISpec {
	if in == nil {
		return nil
	}
	out := new(APISpec)
	in.DeepCopyInto(out)
	return out
}

func (in *PowerDNSServerStatus) DeepCopyInto(out *PowerDNSServerStatus) {
	*out = *in
	if in.Conditions != nil {
		l := make([]v1.Condition, len(in.Conditions))
		for i := range in.Conditions {
			in.Conditions[i].DeepCopyInto(&l[i])
		}
		out.Conditions = l
	}
}

func (in *PowerDNSServerStatus) DeepCopy() *PowerDNSServerStatus {
	if in == nil {
		return nil
	}
	out := new(PowerDNSServerStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *ZoneManagementSpec) DeepCopyInto(out *ZoneManagementSpec) {
	*out = *in
	if in.AllowedNamespaces != nil {
		out.AllowedNamespaces = make([]string, len(in.AllowedNamespaces))
		copy(out.AllowedNamespaces, in.AllowedNamespaces)
	}
}

func (in *ZoneManagementSpec) DeepCopy() *ZoneManagementSpec {
	if in == nil {
		return nil
	}
	out := new(ZoneManagementSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *ObjectRef) DeepCopyInto(out *ObjectRef) {
	*out = *in
}

func (in *ObjectRef) DeepCopy() *ObjectRef {
	if in == nil {
		return nil
	}
	out := new(ObjectRef)
	in.DeepCopyInto(out)
	return out
}

func (in *Zone) DeepCopyInto(out *Zone) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *Zone) DeepCopy() *Zone {
	if in == nil {
		return nil
	}
	out := new(Zone)
	in.DeepCopyInto(out)
	return out
}

func (in *Zone) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ZoneList) DeepCopyInto(out *ZoneList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		l := make([]Zone, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&l[i])
		}
		out.Items = l
	}
}

func (in *ZoneList) DeepCopy() *ZoneList {
	if in == nil {
		return nil
	}
	out := new(ZoneList)
	in.DeepCopyInto(out)
	return out
}

func (in *ZoneList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ZoneSpec) DeepCopyInto(out *ZoneSpec) {
	*out = *in
	out.ServerRef = in.ServerRef
	if in.Masters != nil {
		out.Masters = make([]string, len(in.Masters))
		copy(out.Masters, in.Masters)
	}
	if in.Nameservers != nil {
		out.Nameservers = make([]string, len(in.Nameservers))
		copy(out.Nameservers, in.Nameservers)
	}
	if in.SOA != nil {
		out.SOA = new(SOASpec)
		in.SOA.DeepCopyInto(out.SOA)
	}
	out.DNSSEC = in.DNSSEC
}

func (in *ZoneSpec) DeepCopy() *ZoneSpec {
	if in == nil {
		return nil
	}
	out := new(ZoneSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *SOASpec) DeepCopyInto(out *SOASpec) {
	*out = *in
	if in.TTL != nil {
		v := *in.TTL
		out.TTL = &v
	}
}

func (in *SOASpec) DeepCopy() *SOASpec {
	if in == nil {
		return nil
	}
	out := new(SOASpec)
	in.DeepCopyInto(out)
	return out
}

func (in *ZoneStatus) DeepCopyInto(out *ZoneStatus) {
	*out = *in
	if in.DSRecords != nil {
		out.DSRecords = make([]string, len(in.DSRecords))
		copy(out.DSRecords, in.DSRecords)
	}
	if in.Conditions != nil {
		out.Conditions = make([]v1.Condition, len(in.Conditions))
		for i := range in.Conditions {
			in.Conditions[i].DeepCopyInto(&out.Conditions[i])
		}
	}
}

func (in *ZoneStatus) DeepCopy() *ZoneStatus {
	if in == nil {
		return nil
	}
	out := new(ZoneStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *RRSet) DeepCopyInto(out *RRSet) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *RRSet) DeepCopy() *RRSet {
	if in == nil {
		return nil
	}
	out := new(RRSet)
	in.DeepCopyInto(out)
	return out
}

func (in *RRSet) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *RRSetList) DeepCopyInto(out *RRSetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		l := make([]RRSet, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&l[i])
		}
		out.Items = l
	}
}

func (in *RRSetList) DeepCopy() *RRSetList {
	if in == nil {
		return nil
	}
	out := new(RRSetList)
	in.DeepCopyInto(out)
	return out
}

func (in *RRSetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *RRSetSpec) DeepCopyInto(out *RRSetSpec) {
	*out = *in
	out.ZoneRef = in.ZoneRef
	if in.TTL != nil {
		v := *in.TTL
		out.TTL = &v
	}
	if in.Records != nil {
		out.Records = make([]string, len(in.Records))
		copy(out.Records, in.Records)
	}
}

func (in *RRSetSpec) DeepCopy() *RRSetSpec {
	if in == nil {
		return nil
	}
	out := new(RRSetSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *RRSetStatus) DeepCopyInto(out *RRSetStatus) {
	*out = *in
	if in.Conditions != nil {
		out.Conditions = make([]v1.Condition, len(in.Conditions))
		for i := range in.Conditions {
			in.Conditions[i].DeepCopyInto(&out.Conditions[i])
		}
	}
}

func (in *RRSetStatus) DeepCopy() *RRSetStatus {
	if in == nil {
		return nil
	}
	out := new(RRSetStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *APIGatewaySpec) DeepCopyInto(out *APIGatewaySpec) {
	*out = *in
	if in.Hostnames != nil {
		out.Hostnames = make([]string, len(in.Hostnames))
		copy(out.Hostnames, in.Hostnames)
	}
	if in.ParentRefs != nil {
		out.ParentRefs = make([]APIGatewayParentRef, len(in.ParentRefs))
		copy(out.ParentRefs, in.ParentRefs)
	}
}

func (in *APIGatewaySpec) DeepCopy() *APIGatewaySpec {
	if in == nil {
		return nil
	}
	out := new(APIGatewaySpec)
	in.DeepCopyInto(out)
	return out
}

func (in *PDBSpec) DeepCopyInto(out *PDBSpec) {
	*out = *in
	if in.MinAvailable != nil {
		v := *in.MinAvailable
		out.MinAvailable = &v
	}
}

func (in *PDBSpec) DeepCopy() *PDBSpec {
	if in == nil {
		return nil
	}
	out := new(PDBSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *DNSDist) DeepCopyInto(out *DNSDist) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *DNSDist) DeepCopy() *DNSDist {
	if in == nil {
		return nil
	}
	out := new(DNSDist)
	in.DeepCopyInto(out)
	return out
}

func (in *DNSDist) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *DNSDistList) DeepCopyInto(out *DNSDistList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		l := make([]DNSDist, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&l[i])
		}
		out.Items = l
	}
}

func (in *DNSDistList) DeepCopy() *DNSDistList {
	if in == nil {
		return nil
	}
	out := new(DNSDistList)
	in.DeepCopyInto(out)
	return out
}

func (in *DNSDistList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *DNSDistSpec) DeepCopyInto(out *DNSDistSpec) {
	*out = *in
	if in.Replicas != nil {
		v := *in.Replicas
		out.Replicas = &v
	}
	in.Resources.DeepCopyInto(&out.Resources)
	in.Scheduling.DeepCopyInto(&out.Scheduling)
	if in.BackendRefs != nil {
		l := make([]ObjectRef, len(in.BackendRefs))
		copy(l, in.BackendRefs)
		out.BackendRefs = l
	}
	in.DNS.DeepCopyInto(&out.DNS)
	in.Cache.DeepCopyInto(&out.Cache)
	in.RateLimit.DeepCopyInto(&out.RateLimit)
	in.TLS.DeepCopyInto(&out.TLS)
	if in.PodDisruptionBudget != nil {
		out.PodDisruptionBudget = new(PDBSpec)
		in.PodDisruptionBudget.DeepCopyInto(out.PodDisruptionBudget)
	}
}

func (in *DNSDistSpec) DeepCopy() *DNSDistSpec {
	if in == nil {
		return nil
	}
	out := new(DNSDistSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *DNSDistCacheSpec) DeepCopyInto(out *DNSDistCacheSpec) {
	*out = *in
	if in.Enabled != nil {
		v := *in.Enabled
		out.Enabled = &v
	}
	if in.MaxEntries != nil {
		v := *in.MaxEntries
		out.MaxEntries = &v
	}
}

func (in *DNSDistCacheSpec) DeepCopy() *DNSDistCacheSpec {
	if in == nil {
		return nil
	}
	out := new(DNSDistCacheSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *DNSDistRateLimitSpec) DeepCopyInto(out *DNSDistRateLimitSpec) {
	*out = *in
}

func (in *DNSDistRateLimitSpec) DeepCopy() *DNSDistRateLimitSpec {
	if in == nil {
		return nil
	}
	out := new(DNSDistRateLimitSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *DNSDistTLSListener) DeepCopyInto(out *DNSDistTLSListener) {
	*out = *in
}

func (in *DNSDistTLSListener) DeepCopy() *DNSDistTLSListener {
	if in == nil {
		return nil
	}
	out := new(DNSDistTLSListener)
	in.DeepCopyInto(out)
	return out
}

func (in *DNSDistTLSSpec) DeepCopyInto(out *DNSDistTLSSpec) {
	*out = *in
	in.DoT.DeepCopyInto(&out.DoT)
	in.DoH.DeepCopyInto(&out.DoH)
}

func (in *DNSDistTLSSpec) DeepCopy() *DNSDistTLSSpec {
	if in == nil {
		return nil
	}
	out := new(DNSDistTLSSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *DNSDistStatus) DeepCopyInto(out *DNSDistStatus) {
	*out = *in
	if in.Conditions != nil {
		l := make([]v1.Condition, len(in.Conditions))
		for i := range in.Conditions {
			in.Conditions[i].DeepCopyInto(&l[i])
		}
		out.Conditions = l
	}
}

func (in *DNSDistStatus) DeepCopy() *DNSDistStatus {
	if in == nil {
		return nil
	}
	out := new(DNSDistStatus)
	in.DeepCopyInto(out)
	return out
}
