apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - crd/dns.aetherplatform.cloud_powerdnsservers.yaml
  - crd/dns.aetherplatform.cloud_zones.yaml
  - crd/dns.aetherplatform.cloud_rrsets.yaml
  - crd/dns.aetherplatform.cloud_dnsdists.yaml
  - rbac/rbac.yaml
  - manager/deployment.yaml
